### ISSUE TITLE
Problem when using fbshipit from Composer

### ISSUE THREAD

**Issue by skevy** [facebook/fbshipit#15]
On a new project, where I intend to use fbshipit, I get the following error when I run `hhvm /path/to/composer require facebook/fbshipit`:

```
  [InvalidArgumentException]
  Could not find package facebook/fbshipit at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

After updating my minimum-stability to "dev", it installs fine.

We should either 1) publish with a "stable" stability, or 2) note this in the installation documentation.

**Comment by fredemmott** [comment]
Ack - will probably release 1.0 when things like composer.lock and .gitignore are sorted

**Comment by fredemmott** [comment]
Tagged v1.0.0, should be fixed as that propagates to packagist
