### ISSUE TITLE
hhvm 3.24 needs call-time pass-by-reference fixes

### ISSUE THREAD

**Issue by siddharthab** [facebook/fbshipit#47]
Using composer with HHVM 3.24 needs fixes to fbshipit that are not present in the released version in packagist. Will it be possible to release another version to packagist that is compatible with HHVM 3.24.

Example fixes: https://github.com/facebook/fbshipit/commit/c242594eb4b8c6c3d88e193b7e1e322dc44cd167

Short of releasing a new version, I think the instructions in the README can be updated to include the correct repository to be used with composer.

**Comment by fredemmott** [comment]
It's fixed in master - cc @sdwilsh @zpao re tagging a new release or updating the readme

**Comment by bigfootjon** [comment]
A new release (v2.0.00) has been released with support for the current LTS release of HHVM (4.80)
